services:
  app:
    build:
      context: .
      x-bake:
        tags:
          - ghcr.io/${GITHUB_REPOSITORY}:latest
          - ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}
        platforms:
          - linux/amd64
          - linux/arm64
    ports:
      - "3000:3000"
    env_file:
      - .env
